name: Run Playwright Python Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Playwright browsers
      run: |
        python -m playwright install

    - name: Run Playwright tests
      run: |
        mkdir -p reports
        pytest testcases/

    - name: List files in reports/
      run: ls -l reports

    - name: Upload HTML report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-report
        path: reports/report.html
